[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "Vadzim Dambrouski <pftbest@gmail.com>"
]
categories = ["embedded", "no-std"]
description = "Minimal runtime / startup for MSP430 microcontrollers"
documentation = "https://docs.rs/msp430-rt"
keywords = ["msp430", "runtime", "startup"]
license = "MIT OR Apache-2.0"
name = "msp430-rt"
repository = "https://github.com/pftbest/msp430-rt"
version = "0.1.0"

[dependencies]
msp430 = { git = "https://github.com/japaric/cortex-m", branch = "msp430" }
r0 = "0.2.1"

[features]
abort-on-panic = []
default = ["linker-script"]
# generic linker script
linker-script = []
